.TH "C:/Users/Alfredo/workspace/P4/src/arbitro.java" 3 "Thu Apr 14 2016" "Práctica 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Alfredo/workspace/P4/src/arbitro.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarbitro\fP"
.br
.RI "\fIcreates the main thread with the role of arbiter, is the thread that starts and ends the game is created\&.  public \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica 4 from the source code\&.
