.TH "Pelota" 3 "Thu Apr 14 2016" "Práctica 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pelota \- creates objects that ball, so that every player knows when he has to play, it will be when the ball is in their possession  public  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgolpear\fP (\fBPing\fP p)"
.br
.RI "\fIMethod golpear, serves for a player hits the ball for the other player\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
creates objects that ball, so that every player knows when he has to play, it will be when the ball is in their possession  public 
.SH "Member Function Documentation"
.PP 
.SS "void Pelota\&.golpear (\fBPing\fP p)"

.PP
Method golpear, serves for a player hits the ball for the other player\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPing\fP\fP p 
.RE
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica 4 from the source code\&.
