.TH "Ping" 3 "Thu Apr 14 2016" "Práctica 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ping \- It serves to create game players  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPing\fP (String n, \fBPelota\fP p)"
.br
.RI "\fI\fBPing\fP constructor, serves to create game players \fBPing\fP\&. \fP"
.ti -1c
.RI "String \fBgetNombre\fP ()"
.br
.RI "\fIMethod \fBgetNombre()\fP, return the name of the player\&. \fP"
.ti -1c
.RI "void \fBsetPelota\fP ()"
.br
.RI "\fIMethod \fBsetPelota()\fP, serves to give the ball to a player\&. \fP"
.ti -1c
.RI "void \fBtakeBall\fP ()"
.br
.RI "\fIMethod \fBtakeBall()\fP, serves to remove the ball to the player\&. \fP"
.ti -1c
.RI "boolean \fBhasIt\fP ()"
.br
.RI "\fIMethod \fBhasIt()\fP, used to know if the player has the ball\&. \fP"
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "\fIRun function\&. Running to start the player \fBPing\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
It serves to create game players  public\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ping\&.Ping (String n, \fBPelota\fP p)"

.PP
\fBPing\fP constructor, serves to create game players \fBPing\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIString\fP n, \fBPelota\fP p  public 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String Ping\&.getNombre ()"

.PP
Method \fBgetNombre()\fP, return the name of the player\&. 
.PP
\fBReturns:\fP
.RS 4
String  public 
.RE
.PP

.SS "boolean Ping\&.hasIt ()"

.PP
Method \fBhasIt()\fP, used to know if the player has the ball\&. 
.PP
\fBReturns:\fP
.RS 4
boolean  public 
.RE
.PP

.SS "void Ping\&.run ()"

.PP
Run function\&. Running to start the player \fBPing\fP\&. 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.SS "void Ping\&.setPelota ()"

.PP
Method \fBsetPelota()\fP, serves to give the ball to a player\&. 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.SS "void Ping\&.takeBall ()"

.PP
Method \fBtakeBall()\fP, serves to remove the ball to the player\&. 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica 4 from the source code\&.
