.TH "BasicFrame" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicFrame \- Creates a JFrame object to build the main windows for the Graphics  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicFrame\fP (int type, long initTime, long finalTime, long maxTime, ArrayList< ArrayList< Long >> times)"
.br
.RI "\fI\fBBasicFrame\fP Constructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Creates a JFrame object to build the main windows for the Graphics  public\&. 
.PP
Definition at line 14 of file BasicFrame\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BasicFrame\&.BasicFrame (int type, long initTime, long finalTime, long maxTime, ArrayList< ArrayList< Long >> times)"

.PP
\fBBasicFrame\fP Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype,initTime,finalTime,maxTime,times\fP public 
.RE
.PP
Makes a layout with x rows but 1 col
.PP
Set the layout to the JFrame object
.PP
Configuration of the window
.PP
Adjust dimension
.PP
Set main windows location and allow user to finish the execution by closing the window
.PP
Creates Panel object, the amount of panels it´s equal to the ArrayList size
.PP
Creates a default panel to show general information about the Threads 
.PP
Definition at line 22 of file BasicFrame\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
