.TH "ThreadPanel" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadPanel \- Creates a JPanel object  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadPanel\fP (int id, long init, long end, long max, ArrayList< ArrayList< Long >> times)"
.br
.RI "\fI\fBThreadPanel\fP Constructor\&. \fP"
.ti -1c
.RI "void \fBpaintComponent\fP (Graphics g)"
.br
.RI "\fIvoid paintComponent\&. Creates the Graphic components on the Frame object \fP"
.in -1c
.SH "Detailed Description"
.PP 
Creates a JPanel object  public\&. 
.PP
Definition at line 15 of file ThreadPanel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ThreadPanel\&.ThreadPanel (int id, long init, long end, long max, ArrayList< ArrayList< Long >> times)"

.PP
\fBThreadPanel\fP Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid,init,end,max,times\fP public 
.RE
.PP

.PP
Definition at line 30 of file ThreadPanel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ThreadPanel\&.paintComponent (Graphics g)"

.PP
void paintComponent\&. Creates the Graphic components on the Frame object 
.PP
\fBParameters:\fP
.RS 4
\fIg\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP
Shows the Default panel information
.PP
Shows the panel information and builds the graphic components
.PP
Get the Thread time information
.PP
Builds a graphic string on the panel
.PP
Draws the x-axis line on each panel
.PP
Draws the x-axis values on each panel
.PP
Creates the first point on the x-axis
.PP
Creates the second point on the x-axis
.PP
Unification of first and second point on the x-axis 
.PP
Definition at line 45 of file ThreadPanel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
