.TH "src/ThreadPanel.java" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ThreadPanel.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThreadPanel\fP"
.br
.RI "\fICreates a JPanel object  public\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
