.TH "WithRunnable1_3" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithRunnable1_3 \- A thread is created using the Runnable interface  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A thread is created using the Runnable interface  public\&. 
.PP
Definition at line 7 of file WithRunnable1_3\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void WithRunnable1_3\&.run ()"
Run function\&. Running to start the thread, and displays a message on screen after one second 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 15 of file WithRunnable1_3\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
