.TH "src/WithRunnable2_4.java" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WithRunnable2_4.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWithRunnable2_4\fP"
.br
.RI "\fIFrom the command line parameters receive few threads to create, the program will create and execute the indicated number of threads and displays the total time it takes to run all the threads on the screen\&.  public\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
