.TH "WithRunnable3_2" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithRunnable3_2 \- Case 3\&.2 \&.The program create and execute the threads and show the difference between the interrupted () and interrupted () methods  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithRunnable3_2\fP ()"
.br
.RI "\fI\fBWithRunnable3_2\fP Constructor  public\&. \fP"
.ti -1c
.RI "synchronized void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Case 3\&.2 \&.The program create and execute the threads and show the difference between the interrupted () and interrupted () methods  public\&. 
.PP
Definition at line 8 of file WithRunnable3_2\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WithRunnable3_2\&.WithRunnable3_2 ()"

.PP
\fBWithRunnable3_2\fP Constructor  public\&. 
.PP
Definition at line 15 of file WithRunnable3_2\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "synchronized void WithRunnable3_2\&.run ()"
Synchronized run function\&. Running to synchronized start the threads, and displays a message on screen, after five seconds display other message\&. 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 25 of file WithRunnable3_2\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
