.TH "src/WithRunnable3_2.java" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WithRunnable3_2.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWithRunnable3_2\fP"
.br
.RI "\fICase 3\&.2 \&.The program create and execute the threads and show the difference between the interrupted () and interrupted () methods  public\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
