.TH "src/WithRunnable1_2.java" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WithRunnable1_2.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWithRunnable1_2\fP"
.br
.RI "\fIA thread is created using the Runnable interface  public\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
