.TH "WithRunnable3_3" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithRunnable3_3 \- The program create and execute the thread and and waits for a possible signal to be interrupted by the user\&.  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsendSignal\fP ()"
.br
.RI "\fIMethod sendSignal\&. Send a signal for interrupt execution of thread (signal=true) \fP"
.ti -1c
.RI "boolean \fBgetSignal\fP ()"
.br
.RI "\fIMethod getSignal\&. Observe the state of signal\&. \fP"
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The program create and execute the thread and and waits for a possible signal to be interrupted by the user\&.  public\&. 
.PP
Definition at line 7 of file WithRunnable3_3\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean WithRunnable3_3\&.getSignal ()"

.PP
Method getSignal\&. Observe the state of signal\&. 
.PP
\fBReturns:\fP
.RS 4
boolean  public 
.RE
.PP

.PP
Definition at line 26 of file WithRunnable3_3\&.java\&.
.SS "void WithRunnable3_3\&.run ()"
Run function\&. Running to start the thread, and waits for a possible signal to be interrupted by the user\&. 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 36 of file WithRunnable3_3\&.java\&.
.SS "void WithRunnable3_3\&.sendSignal ()"

.PP
Method sendSignal\&. Send a signal for interrupt execution of thread (signal=true) 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 16 of file WithRunnable3_3\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
