.TH "WithRunnable2_4" 3 "Tue Feb 23 2016" "Practica1_Actividad_1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithRunnable2_4 \- From the command line parameters receive few threads to create, the program will create and execute the indicated number of threads and displays the total time it takes to run all the threads on the screen\&.  public\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithRunnable2_4\fP ()"
.br
.RI "\fI\fBWithRunnable2_4\fP Constructor  public\&. \fP"
.ti -1c
.RI "void \fBsetTime\fP (long time)"
.br
.RI "\fIVoid setTime\&. Add one time in the ArrayList\&. \fP"
.ti -1c
.RI "Iterator< Long > \fBgetTimes\fP ()"
.br
.RI "\fIMethod getTimes\&. Add one time in the ArrayList\&. \fP"
.ti -1c
.RI "synchronized void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
From the command line parameters receive few threads to create, the program will create and execute the indicated number of threads and displays the total time it takes to run all the threads on the screen\&.  public\&. 
.PP
Definition at line 10 of file WithRunnable2_4\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WithRunnable2_4\&.WithRunnable2_4 ()"

.PP
\fBWithRunnable2_4\fP Constructor  public\&. 
.PP
Definition at line 19 of file WithRunnable2_4\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Iterator<Long> WithRunnable2_4\&.getTimes ()"

.PP
Method getTimes\&. Add one time in the ArrayList\&. 
.PP
\fBReturns:\fP
.RS 4
Iterator<Long>  public 
.RE
.PP

.PP
Definition at line 40 of file WithRunnable2_4\&.java\&.
.SS "synchronized void WithRunnable2_4\&.run ()"
Synchronized run function\&. Running to synchronized start the threads, displays a messages on screen and save the times 
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 50 of file WithRunnable2_4\&.java\&.
.SS "void WithRunnable2_4\&.setTime (long time)"

.PP
Void setTime\&. Add one time in the ArrayList\&. 
.PP
\fBParameters:\fP
.RS 4
\fItime\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void  public 
.RE
.PP

.PP
Definition at line 30 of file WithRunnable2_4\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Practica1_Actividad_1 from the source code\&.
